management:
endpoint:
 metrics:
  enabled: true
prometheus:
 enabled: true
endpoints:
 web:
  exposure:
   include: "*"
metrics:
 export:
  prometheus:
   enabled: true
spring:
 spring.h2.console.enabled=true	
 spring.cloud.refresh.enabled=false